# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TPhcXzfRQj9OaLz5wjPXqGt5FEiZadC7

A hospital wants to build a machine learning system that can help doctors predict whether a patient has breast cancer (malignant or benign) based on medical test features.
Your task is to:
Build multiple classification models
Compare single models vs ensemble models
Evaluate model performance using confusion matrix and evaluation metrics
Decide which model is most reliable for real-world medical use
"""

#import libraries

import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    roc_auc_score,
    roc_curve
)

#load dataset

data = load_breast_cancer()
x = data.data
y = data.target

#train_test Split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

#define models

lg = LogisticRegression()
dt = DecisionTreeClassifier()
rf = RandomForestClassifier()

dt = DecisionTreeClassifier(random_state=42)
dt.fit(x_train, y_train)

rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(x_train, y_train)

lg = LogisticRegression(max_iter=1000)
lg.fit(x_train, y_train)

dt_pred = dt.predict(x_test)
rf_pred = rf.predict(x_test)
lg_pred = lg.predict(x_test)

dt_prob = dt.predict_proba(x_test)[:, 1]
rf_prob = rf.predict_proba(x_test)[:, 1]
lg_prob = lg.predict_proba(x_test)[:, 1]

def evaluate_model(name, y_test, y_pred, y_prob):
  print(f'\n{name} Evaluation')
  print('Accuracy:', accuracy_score (y_test, y_pred))
  print('Precision:', precision_score(y_test, y_pred))
  print('Recall:', recall_score(y_test, y_pred))
  print('F1 Score:', f1_score(y_test, y_pred))
  print('ROC AUC Score:', roc_auc_score(y_test, y_prob))

  print('\nconfusion_matrix:\n', confusion_matrix (y_test, y_pred))
  print('\nclassification_report:\n', classification_report(y_test, y_pred))

# Train and evaluate models

evaluate_model('Decision Tree', y_test, dt_pred, dt_prob)
evaluate_model('Random Forest', y_test, rf_pred, rf_prob)
evaluate_model('Logistic Regression', y_test, lg_pred, lg_prob)

"""| Model               | Type     | Reliability          |
| ------------------- | -------- | -------------------- |
| Logistic Regression | Single   | Good & interpretable |
| Decision Tree       | Single   | Easy but overfits    |
| ✅ Random Forest     | Ensemble | **Best & safest**    |

"""